[package]
name = "downloader_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
url = "2.2"
http-downloader = { version = "0.3.2", features = ["all-extensions"] }
indicatif = "0.17.8"
